import assert from 'node:assert/strict';
import { agregheaza, incadreaza, PRAG_PUBLICARE, type ObservatieSalariala } from '../src/lib/observatii-salariale';
import { MESERII, dateMeserieSauEroare, COMPARATII } from '../src/lib/meserii';
import { reperMeserie, textReper } from '../src/lib/repere-meserii';
import offers from '../src/data/repere-oferte-it.json';
import { indicatorMeserie } from '../src/lib/indicator-meserie';
import cor from '../src/data/cor-meserii.json';
const make=(n:number):ObservatieSalariala[]=>Array.from({length:n},(_,i)=>({meserie:'zugrav',titluSursa:'Zugrav',fel:'declarat',suma:'net',minim:4000+i*10,maxim:4000+i*10,data:'2026-08-27',referinta:'https://example.org/record/'+i,id:'source:'+i,perioada:'2026-08',concept:'realizat',norma:'intreaga',experienta:'3-5 ani',reutilizarePermisa:true}));
const options={meserie:'zugrav',suma:'net' as const};
assert.equal(incadreaza('Inginer ofertare','251202')?.slug,'programator');
assert.equal(incadreaza('Programator','251299'),null,'un COR necunoscut nu se deduce din prefix sau din titlu');
assert.equal(incadreaza('Registrator medical'),null);
assert.equal(incadreaza('Asistent medical')?.slug,'asistent-medical');
assert.equal(agregheaza(make(PRAG_PUBLICARE-1),options),null);
assert.equal(agregheaza(make(30),{...options,prag:1}),null,'pragul nu poate fi ocolit');
const a=agregheaza(make(30),options)!;
assert.equal(a.mean,4145); assert.equal(a.median,4145); assert.equal(a.p25,null); assert.equal(a.p75,null);
const b=agregheaza(make(60),options)!;
assert.equal(b.p25,4140); assert.equal(b.p75,4440); assert.equal(b.observatii,60);
assert.equal(agregheaza([...make(20),...make(20)],options),null,'duplicatele nu ridică eșantionul');
for(const patch of [{maxim:9000},{fel:'lege-153' as const},{reutilizarePermisa:false},{perioada:undefined},{id:undefined},{norma:undefined},{experienta:undefined},{minim:NaN},{data:'necunoscut'}]) assert.equal(agregheaza(make(60).map(x=>({...x,...patch})),options),null,JSON.stringify(patch));
for(const patch of [{fel:'anunt' as const},{perioada:'2025-08'},{concept:'baza' as const},{norma:'partiala' as const},{experienta:'junior'}]) assert.equal(agregheaza(make(60).map((x,i)=>i===0?{...x,...patch}:x),options),null,'cohorta mixtă '+JSON.stringify(patch));
assert.equal(agregheaza(make(60).map(x=>({...x,suma:'brut'})),options),null);
assert.equal(agregheaza(make(60).map((x,i)=>({...x,judet:i<29?'Cluj':'Iași'})),{...options,judet:'Cluj'}),null);
const counts:Record<string,number>={};
for(const m of MESERII) {
 const r=reperMeserie(dateMeserieSauEroare(m)); counts[r.kind]=(counts[r.kind]??0)+1;
 assert.equal(r.unit,'lei net/lună');assert.ok(r.url.startsWith('https://'));assert.ok(r.period);assert.ok(r.population);assert.ok(r.note);
 assert.equal(r.n,null);if(r.kind==='external-advertised'){const expected=offers.roles[m.slug as keyof typeof offers.roles];assert.ok(expected);assert.equal(r.median,expected.median);assert.equal(r.p25,expected.p25);assert.equal(r.p75,expected.p75);assert.equal(indicatorMeserie(r).value,expected.median);}else{assert.equal(r.median,null);assert.equal(r.p25,null);assert.equal(r.p75,null);}
 assert.ok(!textReper(r).includes('NaN')); assert.ok(r.value===null || r.value>0);
 const mapping=cor.occupations[m.slug as keyof typeof cor.occupations];assert.ok(mapping);
 assert.equal(m.cor??null,mapping.code);if(m.cor)assert.ok(mapping.name);
 if(r.kind==='sector-context')assert.equal(r.value,dateMeserieSauEroare(m).netObservat);
 if(r.kind==='sector-context'||r.kind==='public-grid')assert.equal(indicatorMeserie(r).value,null);
 if(r.kind==='external-reported')assert.equal(indicatorMeserie(r).value,r.value);
}
assert.equal(reperMeserie(dateMeserieSauEroare(MESERII.find(x=>x.slug==='contabil')!)).value,5000);
assert.equal(reperMeserie(dateMeserieSauEroare(MESERII.find(x=>x.slug==='constructor')!)).kind,'sector-context');
assert.equal(cor.occupations.zugrav.code,'713102');assert.equal(cor.occupations.contabil.code,'331302');
for(const c of COMPARATII)assert.notEqual(c.a.slug,c.b.slug);
console.log('OK: mapări COR, 126 repere și 37 comparații; cohorte, deduplicare, medie/mediană și quartile.',counts);
