import assert from 'node:assert/strict';
import { classifyTitle } from './crawler/occupations.mjs';
import { assess, extractSalary, detailRecord } from './crawler/extract.mjs';
import { deduplicate, summarize } from './crawler/aggregate.mjs';
import { quantile } from './crawler/policy.mjs';
import { allowedByRobots } from './crawler/http.mjs';
for (const [title,slug] of [['Programator CNC','operator-cnc'],['Medic veterinar','medic-veterinar'],['Secretar birou notarial','secretar'],['Asistent medical','asistent-medical'],['Ajutor bucătar',null],['Electrician și instalator',null],['Programator Java','programator'],['Consilier Juridic/Secretar Birou Notarial',null]]) assert.equal(classifyTitle(title).slug,slug,title);
const evidence={sha256:'a'.repeat(64),evidenceFile:'fixture.html',retrievedAt:'2026-09-07T10:00:00Z'};
const base={title:'Contabil',description:'Salariul fix net este 5.000 lei pe luna.',url:'https://example.org/job/1',employer:'Exemplu SRL',source:'fixture',country:'RO',contract:'full-time',active:true,date:'2026-09-01',salary:{from:5000,to:5000,currencyCode:'RON'}};
const now=new Date('2026-09-07T10:00:00Z');
assert.ok(assess(base,evidence,now).accepted);
for(const patch of [{date:'2027-01-01'},{country:null},{country:'DE'},{contract:null},{contract:'part-time'},{active:false},{expires:'2026-08-01'},{description:'Salariu 5.000 lei'},{description:'Tichete de masa 5000 lei net lunar'},{description:'Salariu 5000 EUR net lunar'},{salary:{from:5500,to:5500,currencyCode:'RON'}},{description:'Salariu fix net 5000 lei lunar pentru lucru in Germania'}])assert.equal(assess({...base,...patch},evidence,now).accepted,false,JSON.stringify(patch));
for(const date of [null,'2025-01-01']) assert.ok(assess({...base,date},evidence,now).accepted,'Current active status, not publication recency, defines the census');
assert.ok(assess({...base,description:'Salariu fix brut 5000 lei lunar'},evidence,now).observation.netConversion);
assert.ok(assess({...base,description:'Salariu net 5000 lei lunar + bonus de performanta'},evidence,now).accepted,'Explicitly additional bonus is not part of the base');
assert.equal(assess({...base,active:undefined},evidence,now).accepted,false);
assert.equal(assess(base,{...evidence,retrievedAt:'2025-01-01'},now).accepted,false);
assert.equal(classifyTitle('Ajutoare de bucătar').slug,null);
assert.equal(extractSalary({description:'Salariu net de la 5000 lei lunar'}),null);
assert.equal(extractSalary({description:'Pachet salarial 5000 lei net lunar include tichete'}),null);
assert.equal(extractSalary({description:'Salariu net 5000 lei. Bonus lunar de performanta 1000 lei.'}).monthly,false);
assert.equal(assess({...base,description:'Salariu net 5000 lei'},evidence,now).observation.periodEvidence,'assumed_monthly_full_time');
assert.equal(assess(base,null,now).accepted,false);
assert.equal(extractSalary({description:'Salariu net 5.000–7.000 lei lunar'}).min,5000);
assert.equal(extractSalary({description:'Salariu net 5000 lei sau salariu brut 9000 lei lunar'}),null);
assert.equal(quantile([100,200,300,400],.5),250);
assert.equal(quantile([100,200,300,400],.25),175);
const o=assess(base,evidence,now).observation;
assert.equal(deduplicate([o,{...o,url:o.url+'?tracking=1'}]).length,1);
assert.equal(deduplicate([o,{...o,url:'https://second.org/job',source:'other',sources:['other'],sourceUrls:['https://second.org/job']}]).length,1);
assert.equal(deduplicate([{...o,employerKnown:false,employerKey:null},{...o,url:'https://second.org/job',employerKnown:false,employerKey:null}]).length,2);
const many=Array.from({length:40},(_,i)=>({...o,url:`https://example.org/job/${i}`,employerKey:`firm-${i%20}`,county:`county-${i%5}`,source:i%2?'a':'b',min:4000+i*10,max:6000+i*10}));
assert.deepEqual(summarize(many).medianBounds,{min:4195,max:6195});
assert.equal(summarize(many.slice(0,29)).medianBounds,null);
assert.equal(summarize(many.map(o=>({...o,source:'a'}))).medianBounds,null);
assert.equal(summarize(many.map(o=>({...o,employerKey:'same'}))).medianBounds,null);
assert.equal(summarize(many.map(o=>({...o,periodEvidence:'assumed_monthly_full_time'}))).midpointEstimate,null,'Assumed pay periods alone cannot pass');
const shifted=many.map((o,i)=>({...o,min:i%2?10000:3000,max:i%2?10000:3000}));
assert.ok(summarize(shifted).gaps.includes('source_sensitivity'),'Strongly conflicting portals cannot produce a green light');
assert.equal(extractSalary({description:'Pachet salarial competitiv și beneficii. (venit între 4500–6000 lei net).'}),null);
assert.equal(extractSalary({description:'Salariu net 5000 lei lunar + tichete de masă 800 lei'}).min,5000);
assert.equal(summarize([]).observedRange,null);
assert.equal(allowedByRobots('User-agent: *\nDisallow: /api/\nAllow: /','https://example.org/api/v1'),false);
assert.equal(allowedByRobots('User-agent: *\nDisallow: */pagina\nAllow: */pagina2$','https://example.org/foo/pagina2'),true);
assert.equal(allowedByRobots('User-agent: *\nDisallow: */pagina\nAllow: */pagina2$','https://example.org/foo/pagina20'),false);
const olxJob={title:'Contabil',description:base.description,url:base.url,createdAt:'2026-09-01',validTo:'2026-10-01',status:'active',location:{city:{name:'Brasov'},region:{name:'Brasov'}},params:[{key:'type',value:{key:'full-time'}}],salary:base.salary};
const page={html:'<script>window.__PRERENDERED_STATE__= '+JSON.stringify(JSON.stringify({jobAd:{job:olxJob}}))+';</script>',url:base.url};
assert.ok(assess(detailRecord(page,'olx'),evidence,now).accepted,'OLX detail schema differs from listing schema');
console.log('OK: crawler evidence, units, dates, occupation ambiguity, interval statistics, deduplication and robots policy.');
